### ISSUE TITLE
Hoshi startup issues

### ISSUE THREAD

**Issue by ghost** [1Computer1/hoshi#28]
when attempting to start i Receive the following error

```
[2020-04-02 10:12:35]: [Postgres]: Connection to database has been established successfully.
[2020-04-02 10:12:36]: [Info]: YardBot#8580 is ready to serve!
[2020-04-02 10:12:36]: [Error]: An unhandled promise rejection occured
[2020-04-02 10:12:36]: [Error]: TypeError: this.client.guilds.values is not a function or its return value is not iterable
    at ReadyListener.exec (/home/discord/hoshi/src/listeners/client/ready.js:18:42)
    at HoshiClient.emit (events.js:323:22)
    at HoshiClient.EventEmitter.emit (domain.js:482:12)
    at WebSocketManager.triggerClientReady (/home/discord/hoshi/node_modules/discord.js/src/client/websocket/WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (/home/discord/hoshi/node_modules/discord.js/src/client/websocket/WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (/home/discord/hoshi/node_modules/discord.js/src/client/websocket/WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:311:20)
    at WebSocketShard.EventEmitter.emit (domain.js:482:12)
    at WebSocketShard.checkReady (/home/discord/hoshi/node_modules/discord.js/src/client/websocket/WebSocketShard.js:466:12)
    at WebSocketShard.onPacket (/home/discord/hoshi/node_modules/discord.js/src/client/websocket/WebSocketShard.js:438:16)
    at WebSocketShard.onMessage (/home/discord/hoshi/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/discord/hoshi/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at Receiver.receiverOnMessage (/home/discord/hoshi/node_modules/discord.js/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.EventEmitter.emit (domain.js:482:12)
    at Receiver.dataMessage (/home/discord/hoshi/node_modules/discord.js/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/home/discord/hoshi/node_modules/discord.js/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/home/discord/hoshi/node_modules/discord.js/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/home/discord/hoshi/node_modules/discord.js/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:441:12)
```

**Comment by ghost** [comment]
I'm using node 12
