### ISSUE TITLE
Hoshi startup issues

### ISSUE THREAD

**Issue by LividJava** [1Computer1/hoshi#9]
when attempting to start i Receive the following error

```
Error: Cannot find module 'discord-akairo'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\hoshi\src\util\Extensions.js:1:87)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by 1Computer1** [comment]
Install modules.
